- name: restart docker service
  become: yes
  service: name=docker state=restarted enabled=yes
  
- name: restart kubelet service
  become: yes
  systemd: name=kubelet state=restarted enabled=yes daemon_reload=yes
  
- name: restart ntp service
  become: yes
  service: name=ntp state=restarted enabled=yes